name: win-shell-tests

on:
  workflow_dispatch:
  push:
    branches:
      - ci/win-shell-tests

jobs:
  plugin-tests:
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Run shell plugin tests
        run: cargo test --package tauri-plugin-shell --lib -- --test-threads=1 --nocapture
